### ISSUE TITLE
upgrade don't work with raspberry image install (stuck in release 16)

### ISSUE THREAD

**Issue by Daerdaal** [fforchino/vectorx#15]
i installed ythe raspberry image (downloaded from your link in youtube) (release 16)
the upgrade function (http://escapepod:8070/update.html) don't work for me
everything else seems to work, my robot is listed, setup works, respond to custom intends etc...
but the upgrade never works,
i see that we are now at release 19 but i m still stuck in release 16

**Comment by fforchino** [comment]
Hi, thanks for letting me know!
Please run the update manually:

cd /home/pi/vectorx
sudo update.sh

and attach the output, so we can see what the problem is.

**Comment by Daerdaal** [comment]
i didn't have access to the terminal (as i simply used a pi "alone" and plugged in the sd card).
so i finally just did a clean reinstal and now i'm on realease 19.
Everything works fine
thank you
