### ISSUE TITLE
Support for Vector 2.0

### ISSUE THREAD

**Issue by OfficialArslaanTV** [fforchino/vectorx#17]
I must ask, does this work with Vector 2.0? I have a feeling it won't because Vector 2.0 crashes upon trying to use a face image in the SDK. Correct me if I'm wrong, though

**Comment by fforchino** [comment]
Hmm, I don't have a Vector 2.0 to try. You may try to attach crash logs to
this thread.

Il Gio 10 Ago 2023, 10:22 Arslaan ***@***.***> ha scritto:

**Comment by OfficialArslaanTV** [comment]
Upon using a face image in the SDK, Vector 2.0 Crashes and shows error 915/914 (one or the other) on his face.
