### ISSUE TITLE
Vectorx Compatibility

### ISSUE THREAD

**Issue by Skybird129** [fforchino/vectorx#2]
Hi,
is vectorx also compatible with wire-prod-pod or just wire-pod?
Thanks.

**Comment by fforchino** [comment]
With both, I am using it with a production Vector. You don't need to
recompile Wirepod or Chipper. VectorX should work on top of any existing
Wirepod/Wirepod-prod installation.
If it doesn't in your case, feel free to message me or open an issue on
github.

Regards,
Filippo
