### ISSUE TITLE
webserver start at port 8070 issue

### ISSUE THREAD

**Issue by drascom** [fforchino/vectorx#20]
hi, thank your amazing work. vectorx over wirepod working perfectly but i need to start ./startWebServer.sh manually after reboot raspberry pi. otherwise webserver not reachable.
i put to server path to crontab it is fine but is there any elegance solution for that ?

**Comment by fforchino** [comment]
Hi, the web server is started as a service in the setup:
systemctl enable vectorx-web
systemctl start vectorx-web

After the service is enabled, it should be started at every boot...
