### ISSUE TITLE
Intents not working

### ISSUE THREAD

**Issue by theRoboticarm** [fforchino/vectorx#21]
i have been trying to use the intents with both my voice and the web server but i have not been able to get it to work. it says that it sends the response to the bot but he says nothing back.

**Comment by TheGithubJoshua** [comment]
Same here
@fforchino

**Comment by fforchino** [comment]
Guys, you have a setup problem. We can try a Teamviewer meeting to check what's wrong exactly, since each case needs to be analyzed singularly. PM me on Discord (Vector & Friends server, @Zark75) to arrange one.

**Comment by TheGithubJoshua** [comment]
Issue resolved, just needed to run Initial setup from webUI (which I had to start manually)

**Comment by fforchino** [comment]
Good
