### ISSUE TITLE
Download Link for RPi is broken.

### ISSUE THREAD

**Issue by TheGithubJoshua** [fforchino/vectorx#24]
The link is broken it just says resuming and the download will never finish.

**Comment by fforchino** [comment]
The link isn't broken. The image is just very big, 4GBs, so an HTTP download may be difficult and time out, specially if you have a low bandwidth. Try using a download manager to download it (for example, https://www.freedownloadmanager.org)

**Comment by TheGithubJoshua** [comment]
I was using FDM. But it did work, it just couldn't get the filesize, guess I'm just impatient.
