### ISSUE TITLE
Wire-pod is unable to run chipper on port 443 (using fforchino fork)

### ISSUE THREAD

**Issue by Hugo123456767564577547** [fforchino/vectorx#25]
At the assement bit, it says that wire-pod is unable to run on port 443 ( While using your fork of wire-pod )

**Comment by fforchino** [comment]
What's your setup? RPi? Linux? Windows? If wire-pod is unable to take port 443, then you must have already a server running on it. Port 443 is normally used for HTTPs, perhaps you have XAMPP or some other web server already running.

**Comment by Hugo123456767564577547** [comment]
I disabled wire-pod.service and ran it like a normal setup, and it could use 443, it’s a problem with wire-pod.service

**Comment by Hugo123456767564577547** [comment]
Raspberry pi 3 A+ Raspberry pi os lite, with SSH Enabled.

**Comment by Hugo123456767564577547** [comment]
I updated vector to 2.0.1 now he uses port 8084, but it still begs the question why?

**Comment by Hugo123456767564577547** [comment]
It just, worked, what? it just kinda woke up? idk but hey its closed
