### ISSUE TITLE
SSH Login Data Raspi4 Image

### ISSUE THREAD

**Issue by mikes-techzone** [fforchino/vectorx#34]
Hi, first of all, thank you very much for your work. 

After a few initial difficulties I was able to connect my Vector.
Now I have seen the German translations and thought nice try :) 

When I tried to change them I failed at the SSH login.

Maybe I just overlooked it. Which SSH login data are on your Raspi4 image?

**Comment by mikes-techzone** [comment]
I got it out :) 

for all who are facing the same problem, the password for the user "pi" is "vectorx"

**Comment by fforchino** [comment]
pi / vectorx I think it's written on github. Unfortunately I don't have
time for new developments lately but that was a quick one
