### ISSUE TITLE
How do you uninstall?

### ISSUE THREAD

**Issue by Manic137** [fforchino/vectorx#6]
There doesn't seem to be a way to uninstall, even when I kill the processes, vectorx installs itself directly into wire-pod, and still runs its weather and whatnot, I would prefer the original animations even if the new ones has some new additions. On top of that, I have some issues where vector would freeze in between telling the weather, and ton of other issues, just don't feel like resolving them as I have a heavy week, might come back to it later when I have more free time and less projects to work on

**Comment by fforchino** [comment]
I will add an uninstall script, basically it just removes all VectorX
services and de-injects the VectorX custom intent from Wirepod.

**Comment by Manic137** [comment]
Thank you

**Comment by fforchino** [comment]
Added to RELEASE_12

**Comment by Manic137** [comment]
How do I update vectorx from the old version? Update.sh doesn't download new files, seems to only update chipper and not vectorx

**Comment by Manic137** [comment]
I have removed the directory and reclone the git, then uninstalled successfully, thank you. You should also have a way to update the files added

**Comment by fforchino** [comment]
It's a git repository. You update it using git, normally.

git pull

The update.sh does everything though and even if it is meant to be used by
the web front end, it should work.
It does update all the repos, rebuild and calls the setup.sh in silent
mode.But it won't work if you have made some changes to the repository, in
this case you have to commit or stash your changes and manually update
through git.

Il Ven 10 Mar 2023, 05:27 Manic137 ***@***.***> ha scritto:

**Comment by Manic137** [comment]
Weird, thanks, I'll pull it next time
