### ISSUE TITLE
Update script and potentially install script runs as user "pi"

### ISSUE THREAD

**Issue by Manic137** [fforchino/vectorx#9]
```
Checking for updates...
Stopping Services
[sudo] password for manicquinn: 
Updating Wire-Pod...
runuser: user pi does not exist
Building chipper just in case...
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
Updating VectorX...
runuser: user pi does not exist
```
This assumes everyone has a pi user, but I don't.

**Comment by fforchino** [comment]
The update script is meant to be used by the RPi4 VectorX image only, that has a single user named "pi" and VectorX pre-installed under /home/pi/vectorx. I will see if it's possible to make it more generic.

**Comment by Manic137** [comment]
I run mine on ubuntu

**Comment by fforchino** [comment]
Fixed in RELEASE_13
Update manually to this release with "git pull". Then you can run ./update.sh and it should work, whatever your user is.
Or you can just use the web server and go check and apply updates.
